![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
import numpy as np

In [ ]:

my_array = np.arange(10)
my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
my_array = np.arange(10)
x =my_array[8:6:-1]
print(x)

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
y = my_array[2::-1]
print(y)

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
matrix = np.arange(1,21).reshape(4,5)
print(matrix)
print(matrix[::-1,::-1])#invertir la matriz
np.flip(matrix)#otra forma de invertir

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
matriz = matrix[:2, :2]#en la fina desde la posicion 0 hasta la 2-1, en la columna desde la posicion 0 hasta la 2-1
print(matriz)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
matriz = matrix[::2, ::2]#igual que antes, solo he añadido el paso en cada coordenada
print(matriz)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
matriz = matrix[:3:1, ::-1]#sacame de la fila 0 a la 3/ sacame todas las columnas en orden inverso
print(matriz)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
y=np.where(x == "Loro", x, "_" )
z = np.array(x == "Loro")
print(z)
print(y)
print(x[(x == "Loro") ])
np.extract(x=="Loro",x)





[ True False False  True False]
['Loro' '_' '_' 'Loro' '_']
['Loro' 'Loro']


array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [ ]:
secuencia = np.arange(20)
print(secuencia)
array_sec =secuencia.reshape(2,5,2)
print(array_sec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
array10= np.zeros(10)
print(array10)
#nos indica la memoria consumida para crear este array
print(array10.nbytes)#cuanto ocupa el array bytes
print(array10.itemsize)
print(array10.dtype)#va a ocupar 64 bits



array10[4]=1
print(array10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
8
float64
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
arr_10=np.full(10,0, dtype=np.int8)#fuerzo que ocupe menos memoria(puede recoger 256 elementos)
print(arr_10)
print(arr_10.nbytes)#cuanto ocupa el array
print(arr_10.itemsize)
print(arr_10.dtype)


[0 0 0 0 0 0 0 0 0 0]
10
1
int8


In [6]:
#si le damos un valor que se pasa del tamaño que le hemos impuesto, empieza a contar de 0:
arr_10[0]=128 
print(arr_10)
#van del [-128,127]
'''En este caso nos ha dado fallo por esatr fuera de rango, pero es como un reloj, se resetea'''

OverflowError: Python integer 128 out of bounds for int8

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [8]:
vector = np.arange(10,50)
print(vector)
v1 = vector[::-1]
print(v1)

invertir = np.flip(vector)
print(invertir)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [12]:
lista =np.array([1,2,0,0,4,0])
posiciones = np.where(lista != 0)
print(posiciones)
print(type(posiciones))

(array([0, 1, 4]),)
<class 'tuple'>


In [5]:
def ejer_12(vector):
    return np.where(vector != 0)[0]#con [0] hago que me devuelva directamente un array, si no me da una tupla

In [6]:
lista =np.array([1,2,0,0,4,0])
ejer_12(lista)

array([0, 1, 4])

In [7]:
np.nonzero(lista)[0]

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
matrix13 = np.random.random((10,10))#aqui los valores van de 0-1
print(matrix13)
print(f"El menos de la matriz es: {np.min(matrix13)}")
print(f"El mayor de la matriz es: {np.max(matrix13)}")

[[0.54891527 0.01832161 0.44634587 0.24338243 0.94740221 0.26624196
  0.51796568 0.63866101 0.73450781 0.56956008]
 [0.8118897  0.77109448 0.35070876 0.86254444 0.56151135 0.50688817
  0.56547045 0.18254331 0.16342817 0.8170223 ]
 [0.16285053 0.77951366 0.17308404 0.65661206 0.08366687 0.56573841
  0.4434777  0.25421406 0.36949668 0.32468728]
 [0.13686917 0.24207835 0.65987639 0.79020812 0.7523322  0.10514203
  0.94191827 0.38376869 0.10620324 0.88132528]
 [0.3657699  0.77171851 0.08432092 0.95228685 0.26413379 0.88594146
  0.52229141 0.87608196 0.58582949 0.51666497]
 [0.77694814 0.15686363 0.83697166 0.76432188 0.17893453 0.76120451
  0.57403171 0.33340204 0.81213955 0.37349201]
 [0.88336959 0.57091032 0.51504773 0.49362967 0.06813838 0.23726032
  0.39383511 0.39152351 0.27338543 0.71552705]
 [0.59061871 0.78082816 0.44188934 0.46482967 0.70262069 0.41189764
  0.89180174 0.9858008  0.72565135 0.63492657]
 [0.51372311 0.40533315 0.6909378  0.07910058 0.73577397 0.47781344
  0.83385361

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vec30= np.random.random(30)
media = np.mean(vec30)
print(f"La media del vector es: {media}")
print(vec30)

La media del vector es: 0.4163646948281848
[0.00526874 0.63602341 0.99422646 0.76320804 0.57043638 0.32078439
 0.20098483 0.59379801 0.53585685 0.124916   0.73313109 0.5604683
 0.41070649 0.01248771 0.57032173 0.16799454 0.09062547 0.1994644
 0.26702829 0.1918903  0.92480755 0.53704722 0.23290512 0.40463989
 0.49115716 0.71180379 0.23035493 0.57041773 0.37767544 0.06051059]


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
array_cuadrado = np.zeros((5,5))


for i in range(5):
    for j in range(5):
        if i==0 or i ==4 or j==0 or j ==4:
            array_cuadrado[i][j]=1

print(array_cuadrado)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
array_cuadrado = np.zeros((5,5))

array_cuadrado[: ,0]=1
array_cuadrado[: ,-1]=1

array_cuadrado[0, : ]=1
array_cuadrado[-1, : ]=1
print(array_cuadrado)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
ejer_15 =np.ones((5,5))
ejer_15[1:-1,1:-1]=0#menos en la primera y ultima columna y fila, pon ceros
#de la 1 a la ultima(la anterior)
print(ejer_15)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
def ejer_15(tamaño):
    matrix = np.full(tamaño,1)
    matrix[1:-1,1:-1]=0
    return matrix

In [6]:
matrix15 = ejer_15((10,10))
print(matrix15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
mat16 = np.zeros((8,8))

#las filas pares llenan de unos las columnas impares
mat16[::2,1::2]=1
#las filas impares llenan de unos las columnas pares
mat16[1::2,::2]=1
print(mat16)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
mat16 = np.ones((8,8))

for i in range(8):
    for j in range(8):
        if (i + j)%2 ==0:#si sumo las posicione y las divido entre dos (la coordenada es par) en esa coordenada me pones un cero si no pues nome lo ca,bia pq es una matriz de unos
            mat16[i,j]=0


print(mat16)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
#es como un repetidor de array dependiendo de las dimensiones que le diga
mat17 =np.array([[0, 1, 0, 1, 0, 1, 0, 1],
                [1, 0, 1, 0, 1, 0, 1, 0]])
np.tile(mat17, (4,1))#sacame el array 4 veces con un salto de linea entre cada iteracion

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
a =np.array([[1,0],
          [0,1]])
x=np.title(a,(4,4))#el primer cuadrado se repite 4 veces a lo ancho y el segundo 4 veces a lo largo
print(x)

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [10]:
mat18 = np.random.random((5,5))
print(mat18)
media = np.mean(mat18)
print(f"La media es {media}")
print(f"La desviacion estandar es: {np.std(mat18)}")
normalizar = (mat18 - media / np.std(mat18))
print(f"Los datos normalizados son {normalizar}")

[[0.72758555 0.99851872 0.41962437 0.1942933  0.46585948]
 [0.85589659 0.18148576 0.88805835 0.01523346 0.93511887]
 [0.22281637 0.00478867 0.79690947 0.02944779 0.38948808]
 [0.85802424 0.09801349 0.58781735 0.40294159 0.45723519]
 [0.68260778 0.24202933 0.70092077 0.73356581 0.03339803]]
La media es 0.4768671371577075
La desviacion estandar es: 0.31976068439787386
Los datos normalizados son [[-0.76373956 -0.49280639 -1.07170073 -1.29703181 -1.02546563]
 [-0.63542852 -1.30983935 -0.60326676 -1.47609164 -0.55620623]
 [-1.26850874 -1.48653644 -0.69441564 -1.46187732 -1.10183703]
 [-0.63330086 -1.39331162 -0.90350775 -1.08838352 -1.03408991]
 [-0.80871733 -1.24929578 -0.79040434 -0.75775929 -1.45792708]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [14]:
secuencia = np.arange(10)
print(secuencia)
#hago una copia para no variar la original y la renombro

lista =secuencia.copy()
lista1 =secuencia.copy()

#lista[3:9]=-1
print(lista)
lista[(lista>=3) & (lista<=8)]=-1
print(lista)
x1,x2 = np.split(lista, 2)
print(x1)
print(x2)
#vemos que la original no se ha modificado
print(secuencia)

#negar es lo contrario del valor
lista1[(lista1>=3) & (lista1<=8)]*= -1
print(lista1)
#and &
#or |
#not ~


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9]
[ 0  1  2 -1 -1]
[-1 -1 -1 -1  9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]
